Little upgrades + New section "Templates"
brettz9/awesome-jsdoc pull request #1
Opened 2020-08-18 17:24 UTC by you-create

- Updated `README.md` and `CONTRIBUTING.md` appropriately (e.g. uniform format among list entries)
- Renamed `contributing.md` to `CONTRIBUTING.md` (more often seen capitalized) and `license-mit.txt` to `LICENSE.txt`
- Added section _Templates_ to the Awesome list

2020-08-21 13:43 UTC, brettz9 requested changes
Some useful contributions, if you can make the requested adjustments, thanks!

2020-08-21 13:43 UTC, brettz9 commented on CONTRIBUTING.md
> -- New categories or improvements to the existing categorization are welcome.
Some very good contributions! (I hadn't really reviewed this too carefully originally as it was just taken from another such list.)

I think that the above line should be added back though that categorization improvements are welcome.

2020-08-21 13:43 UTC, brettz9 commented on README.md
> +  Markdown-formatted docstrings to HTML in output.
For these items, I'd like to keep having a description indicating how it was related to JSDoc. Yes, of course these are all related to JSDoc, but one might have to think about whether this is Markdown in JSDoc to HTML or Markdown to JSDoc in HTML, etc. I'd like to keep that explicit.

2020-08-21 13:43 UTC, brettz9 commented on README.md
> +
I think `Converts` is better than `Convert` as it is describing the previous entry in the list as third person "it". I think that fits in more with an objective description than a series of directive (even if advertisements favor the more active voice, I favor the descriptive).

2020-08-21 13:43 UTC, brettz9 commented on README.md
Cool!

2020-08-21 13:43 UTC, brettz9 commented on README.md
> -  types everywhere?.)
I'd appreciate if you could at least add this back as an HTML comment. :-)  I think it is an absolutely critical area for development (even while I understand it may not fit too well with the genre, it is, as you say, a "curated" list where we can have our own opinions). :-)

2022-05-27 03:35 UTC, closed without merging

2025-02-25 04:55 UTC, Yedfree approved these changes